"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const MessController_1 = require("../controllers/MessController");
const router = (0, express_1.Router)();
router.get('/', MessController_1.MessController.getAll);
router.get('/:id', MessController_1.MessController.getById);
router.post('/', MessController_1.MessController.create);
router.put('/:id', MessController_1.MessController.update);
router.delete('/:id', MessController_1.MessController.delete);
exports.default = router;
